WIP: Add overwrite checks
magic-wormhole/magic-wormhole.rs pull request #107
Opened 2021-01-22 23:15 UTC by brightly-salty

Fixes #105 

Currently a WIP as there are some move issues in the accept function.

2021-01-25 14:00 UTC, iyzana commented on src/bin/main.rs
> +        "Receive file '{}' (size: {} bytes)? (y/N) ",
With a prompt like `(y/N)` (with an uppercase N) i would expect that simply pressing enter means no, but that is not the case with the `ask_user` function.

2021-01-25 14:26 UTC, brightly-salty commented on src/bin/main.rs
> +        "Receive file '{}' (size: {} bytes)? (y/N) ",
Probably a typo in this case.. Maybe the ask_user function can have a boolean parameter which determines the default answer?

2021-01-25 14:42 UTC, iyzana commented on src/bin/main.rs
> +        "Receive file '{}' (size: {} bytes)? (y/N) ",
A good typo in this case :)
Sound good!

2021-01-31 13:03 UTC, piegamesde requested changes
Thank you so far! I've only got a few minor requests for now. Two things that I'd like to see happen in the future (however not necessarily in this PR if you don't want to):

- Don't make the user interaction in the library itself, but instead expose the conflict in the API somehow. Then, applications can do their custom input dialog if they want to.
- Add a few tests that try to receive a file but it already exists etc.

P.S.: On GitHub, you mark pull requests as "draft" instead of prepending "WIP" to the title

2021-01-31 15:49 UTC, brightly-salty commented
Okay @piegamesde I've made the changes I'm open to implementing the other changes (exposing it in the API, and adding tests) but I will probably need more guidance/mentoring to do something like that. I can continue in this PR or we can merge it and open a new one for those changes, whichever you prefer.

2021-01-31 16:37 UTC, piegamesde commented
I've had a look at it and the tests are in a rather bad shape at the moment, so doing it here would probably be scope creep. Regarding the API, I propose the following: The check is moved into `main.rs` and `accept` takes in a `overwrite: bool`. This allows for the following behavior:

- The application will check the file if it already exists and then pass the user's answer. If it doesn't, it will pass `false`. This should prevent any TOCTTOU bugs.
- One can safely always say `false` and never overwrite anything (for a future noninteractive mode)
- One can also pass `true` if the destination location is a temporary folder etc. (this will probably be useful for the tests as well)

2021-01-31 16:44 UTC, brightly-salty commented
@piegamesde So will the `RecieveRequest::accept()` function still check for overwriting? If it does, then we're duplicating effort in the application and the library.

2021-01-31 17:10 UTC, piegamesde commented
We have one explicit check and one implicit one when opening the file. If we move the check into the application, the library needs not do it anymore. The implicit check happens when we open the file: if `overwrite = false`, the `create_new` function will fail if the file already exists. If `overwrite = true`, the `truncate` option will handle existing files. By the way this still needs to be implemented, the starting point there is `let mut file = File::open` in `send_records`. I haven't tried it out myself, but your current code *should* fail to overwrite any files even when the user confirms it.

2021-02-01 12:52 UTC, piegamesde requested changes
Two minor details and then this is good to go. As our CI is still WIP, please manually do the following things:

- Run `cargo +nightly fmt` for consistent code style
- Rewrite the history in pretty, otherwise I'll squash it into one commit if you're fine with that :)
- Tests
    - Send yourself a file
    - Send it again and check the correct behavior if you accept/deny to overwrite it.
- Regression tests
    - Send a file to yourself
    - Send it again, but using the python implementation as sender
    - And again, but using the python implementation as receiver

2021-02-01 12:52 UTC, piegamesde commented on src/transfer.rs
> +use crate::util::ask_user;
Unused import warning

2021-02-01 12:52 UTC, piegamesde commented on src/bin/main.rs
> +    let overwrite = !req.filename.exists()
This may be prone to race hazards (time to check vs time of use). The idea to resolve this is that if `!req.filename.exists()`, the user is not asked for confirmation, but `overwrite = false`. Therefore, a race hazard will not cause any files to unexpectedly be overwritten.

2021-02-01 12:58 UTC, brightly-salty commented on src/bin/main.rs
> +    let overwrite = !req.filename.exists()
Would this fix that? 
```rust
    let overwrite = if req.filename.exists() {
        ask_user(
            format!("Override existing file {}?", req.filename.display()),
            false,
        )
        .await
    } else {
        false
    };
```

2021-02-01 13:04 UTC, piegamesde commented on src/bin/main.rs
> +    let overwrite = !req.filename.exists()
Yes

2021-02-17 11:09 UTC, piegamesde commented
I just tried it out and I got a panic: `thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: TransitType { abilities_v1: [DirectTcpV1, RelayV1], hints_v1: [DirectTcpV1(DirectHint { priority: 0.0, hostname: "192.168.1.1", port: 40900 }), RelayV1(RelayHint { hints: [DirectHint { priority: 0.0, hostname: "transit.magic-wormhole.io", port: 4001 }] })] }', src/transfer.rs:326:64`

Also a small typo in the dialog: Override=>Overwrite.

2021-02-21 12:06 UTC, piegamesde commented on src/transfer.rs
> +                Arc::try_unwrap(self.other_side_ttype.clone()).unwrap(),
This should not work, because you are cloning the reference counter instead of the inner value. I think you want something like `(*self.other_side_ttype).clone(),` instead.

2021-03-20 23:26 UTC, merged

2021-03-20 23:27 UTC, piegamesde commented
Thank you for your contribution. I hope you don't mind me going ahead on the last meters :)