Refactor send-many
magic-wormhole/magic-wormhole.rs pull request #117
Opened 2021-03-17 15:31 UTC by tau3

Hi! This PR addresses #95

2021-03-17 15:47 UTC, piegamesde commented
Woah, that's awesome, many thanks!

Please be patient for this to get merged however, my backlog is a bit full these days

2021-03-23 10:31 UTC, piegamesde commented
Can you please rebase your changes on master?

2021-03-23 12:00 UTC, tau3 commented
done. btw, looks like you have some broken unit tests in master (`core::test::test_file_rust2rust`)

2021-03-23 19:09 UTC, piegamesde commented
Yeah, I fucked up, see https://github.com/magic-wormhole/magic-wormhole.rs/pull/116#issuecomment-804493278

2021-03-23 19:34 UTC, piegamesde requested changes
Looks great so far

2021-03-23 19:34 UTC, piegamesde commented on src/bin/main.rs
> +                info!("Sent {} of {} bytes", sent, total);
I think having an independent progress bar for each transfer would be best here. I haven't looked into how feasible this is though.

2021-03-23 19:34 UTC, piegamesde commented on src/bin/main.rs
> +    while time.elapsed()? < one_hour {
Why not use `Instant` instead of `SystemTime`? Its `elapsed()` is monotonic so it can't fail.

2021-03-23 19:34 UTC, piegamesde commented on src/bin/main.rs
> +    let one_hour = Duration::from_secs(3600);
Would be cool if you went the extra mile and made this a CLI parameter.

2021-03-23 19:34 UTC, piegamesde commented on src/bin/main.rs
> +    while time.elapsed()? < one_hour {
Also, I think there is some use case for limiting the attempts based on count as well. I'll have to calculate how many attempts are acceptable without having an increased risk of the communication being cracked. Maybe increase the default generated password length for `send-many` in order to counter this?

2021-03-23 19:34 UTC, piegamesde commented on src/bin/main.rs
> +                }
I think I configured the formatter to use trailing commas. Maybe it's a nightly only feature, so try with `cargo +nightly fmt` and this change should go away.

2021-03-24 17:18 UTC, tau3 commented on src/bin/main.rs
> +    while time.elapsed()? < one_hour {
i'm not sure it can be answered without calculation :)

2021-03-24 23:06 UTC, piegamesde commented
I'm trying it out, and for some reason the help on that sub-command is empty? I can't tell any obvious cause for this though.

2021-03-25 11:11 UTC, tau3 commented
it had been hidden by custom help message - fixed

2021-03-25 21:04 UTC, piegamesde commented
I somehow always get a 'crowded' error from the server. But I also get this on master. I suspect that it's the same bug that's causing the tests to fail at the moment. Unless you want to work on this some more, I think I'll merge this now and then fix it together with the tests in the (hopefully) near future.

2021-03-26 23:39 UTC, merged