Add nameplates fn
magic-wormhole/magic-wormhole.rs pull request #184
Opened 2023-02-28 08:27 UTC by JustusFT

Ref: https://github.com/magic-wormhole/magic-wormhole.rs/issues/183

2023-02-28 10:07 UTC, piegamesde requested changes
Looking okay so far. One thing I'm unsure about is any public API: as proposed here, you'd need access to the `RendezvousServer` in order to make the call. As far as I can tell, it is only exposed when using `Wormhole::connect_custom`.

I don't know what the intended use cases are\*, so maybe this is all the necessary API.

\* autocompletion is [out](https://github.com/magic-wormhole/magic-wormhole/issues/471)

2023-02-28 10:07 UTC, piegamesde commented on src/core/rendezvous.rs
> +    pub async fn nameplates(&mut self) -> Result<Vec<Nameplate>, RendezvousError> {
```suggestion
    pub async fn list_nameplates(&mut self) -> Result<Vec<Nameplate>, RendezvousError> {
```

Also add a short doc comment about what this does and when it can be used.

Is the usage of this command restricted in any way by the state machines? As in, is it even allowed to execute it after having claimed a nameplate? Is it allowed after the nameplate was released?

2023-03-01 01:55 UTC, JustusFT commented on src/core/rendezvous.rs
> +impl std::fmt::Display for NameplateList {
The compiler says the macro can't be applied on `Vec<T>` types, so I made the impl manually
I get this error:
```
error[E0277]: `Vec<Nameplate>` doesn't implement `std::fmt::Display`
  --> src/core/rendezvous.rs:77:24
   |
77 | #[derive(Clone, Debug, derive_more::Display)]
   |                        ^^^^^^^^^^^^^^^^^^^^ `Vec<Nameplate>` cannot be formatted with the default formatter
   |
   = help: the trait `std::fmt::Display` is not implemented for `Vec<Nameplate>`
   = note: in format strings you may be able to use `{:?}` (or {:#?} for pretty-print) instead
   = note: this error originates in the derive macro `derive_more::Display` (in Nightly builds, run with -Z macro-backtrace for more info)

```

2023-03-01 02:01 UTC, JustusFT commented
I updated the linked issue with more information about the use case.
Currently I want the application to exit if the receiver put in a code with an unclaimed nameplate.
Would it be better to include the nameplate validation inside `connect_with_code` so we don't need to call `connect_custom`? This would be similar to how wormhole-william does it

2023-03-01 20:48 UTC, piegamesde commented
That would be okay to do, however it should be opt-in, as in most scenarios you actually don't want such a check.

2023-03-03 05:34 UTC, JustusFT commented on src/core/rendezvous.rs
> +    pub async fn nameplates(&mut self) -> Result<Vec<Nameplate>, RendezvousError> {
I updated the function to have a doc comment. Let me know if the wording is okay

It can be called at any time. (before claiming a namplate, after claiming a nameplate, and after releasing a nameplate)

2023-03-03 11:33 UTC, piegamesde commented on src/core.rs
> +            if !nameplates.iter().any(|e| e.0 == nameplate.0) {
Something more like

```suggestion
            if !nameplates.contains(&nameplate)
```

2023-03-03 11:33 UTC, piegamesde commented on src/core/rendezvous.rs
> +impl std::fmt::Display for NameplateList {
Try in combination with `#[display(fmt = "{:?}", _0)]`

2023-03-03 11:36 UTC, piegamesde requested changes

2023-03-03 11:36 UTC, piegamesde commented on src/core/test.rs
> +                Wormhole::connect_with_code(transfer::APP_CONFIG.id(TEST_APPID), code, false)
Let's set this to true where possible to also test the happy case. (Also in the other tests)

2023-03-07 11:57 UTC, piegamesde approved these changes
Please make the commit history pretty (squashing everything together is okay too) and then we are good to go.

2023-03-08 01:30 UTC, JustusFT commented
@piegamesde I squashed and rebased :+1:

2023-03-08 22:34 UTC, merged