Combine connect methods
magic-wormhole/magic-wormhole.rs pull request #195
Opened 2023-04-30 21:17 UTC by wuan

2023-05-01 09:35 UTC, piegamesde commented
Judging from the diff of the tests, I think this is a downgrade in API usability. Moreover, importing enum variants is frowned upon in many contexts (although I think it is kind of fine here?).

I think you can still make your deduplication by having the old API methods as shims delegating to the actual generic implementation.

Also keep in mind the use-case of connecting directly to a mailbox without nameplate, even though we don't currently make use of it. This is definitely a feature that will eventually be supported some time in the future.

2023-05-01 09:51 UTC, wuan commented
> Judging from the diff of the tests, I think this is a downgrade in API usability. Moreover, importing enum variants is frowned upon in many contexts (although I think it is kind of fine here?).

Having boolean values in APIs is some kind of anti-pattern. Enums help to group parameters for the different use cases and use names.

> I think you can still make your deduplication by having the old API methods as shims delegating to the actual generic implementation.

This is about deduplication and removing boolean flags from argument lists. 

> Also keep in mind the use-case of connecting directly to a mailbox without nameplate, even though we don't currently make use of it. This is definitely a feature that will eventually be supported some time in the future.

The change should not have removed any use-cases which have existed before. Can you give an example what will not work after the change?

2023-05-01 21:53 UTC, piegamesde commented
> Having boolean values in APIs is some kind of anti-pattern. Enums help to group parameters for the different use cases and use names for clarification.

I agree in general, but this was not my point. I was referring to having `WormholeConnect::GenerateCode` etc. in the file's global scope. But then if you don't import it like that the simple `WithCode` becomes `WormholeConnect::WithCode` or even `magic_wormhole::WormholeConnect::WithCode` …

> The change should not have removed any use-cases which have existed before. Can you give an example what will not work after the change?

I'm not saying it does, I'm just saying to keep it in mind so that it doesn't.

-----

Let's take a step back and explore some more API ideas that might our current issues with it.

- We could do a full-blown builder pattern
  - It would require two structs for the type state, and one of them would have a `expect_claimed_nameplate()` function or something like that
- We could have `WormholeConnect::connect(self, AppConfig)`
  - Downside is that the `Wormhole` struct has no constructor on itself anymore, but that's not uncommon in Rust APIs
  - Maybe call it `WormholeConnector` then

2023-05-02 05:58 UTC, wuan commented
> I agree in general, but this was not my point. I was referring to having `WormholeConnect::GenerateCode` etc. in the file's global scope. But then if you don't import it like that the simple `WithCode` becomes `WormholeConnect::WithCode` or even `magic_wormhole::WormholeConnect::WithCode` …

I do not see a problem here, as it still will be type safe and the user of the library can decide what to do adapting to the use case. 

And yes, a builder pattern can be added on top of this any time.

2023-05-03 19:39 UTC, wuan commented
> Hmm, I am sorry for being nitpicky but I'm still not convinced.
> 
> * The motivation of this PR is to remove the bool argument in the function signature, which it does and is a good thing.
> * The PR also claims to remove code duplication by merging two similar functions, but actually it has little effect. If you look at `initiate_connect`, almost all the relevant business logic is within the match/case distinction, except for a couple of lines of boilerplate code for input and return. But also this is not surprising, as all the duplicated code already got factored out into `connect_custom`.

The old code duplicates the function definition, calling `RendezvousServer::connect(...)` and building up the response. That is already duplication.

> * The `connect_with_code` and `connect_without_code` functions, while being similar, nevertheless have a distinct return type. This is now modeled using `connect` and `initiate_connect` functions. But which one of those should be used when? Previously the function signature just took care about that part, now users must think about it.

`initiate_connect(...)` is only there for the test setup. It should be removed from the public API to avoid confusion. Even worse, the slightly different return type of `connect_without_code(...)` has been added to a public API only for purpose of internal testing. That is something I would call unexpected and confusing.

> So overall this feels like a "one step forward one step back" kind of change to me. (Don't get me wrong, the proposed API is okay, but I don't see the value in replacing one okay API with small flaws by another API with other small flaws). I think this could be improved so that it does not have these problems, we could discuss that if desired. But as of now, IMHO this is mainly about the boolean argument flag, and for that there is a minimal solution:
> 
> You can give the argument a name by wrapping it in a tuple struct:
> 
> ```
> /// Wormhole.connect_with_code(config, code, Allocate(false))
> #[derive(Clone, Copy, Debug, Default, Eq, PartialEq)]
> pub struct Allocate(pub bool);
> ```

I'm still not convinced and I propose to hide `initiate_connect(...)` from the user. In the end just having a single connect method which can be configured by a type safe parameter (Enums allow grouping of required parameters per use case) seem to be quite promising, especially as there are more ways to connect in the pipeline.

Besides that, I do not see the difference between importing a struct or an Enum.

> 
> The Gtk-rs bindings already make use of this pattern to map boolean arguments from the C side, and quite successfully so: https://gtk-rs.org/gtk-rs-core/stable/latest/docs/glib/signal/struct.Inhibit.html https://gtk-rs.org/gtk-rs-core/stable/latest/docs/glib/source/struct.Continue.html
> 
> Also I chose `Allocate` as the name, because if we are touching the `expect_claimed_nameplate` flag while we are at it I'd like to invert it and call it "allocate", in accordance with the spec proposal. (It is an improvement Meejah came up with, and I really like it so why not also apply it here)

Renaming the boolean flag to "allocate" should be straightforward.

2023-05-03 20:15 UTC, piegamesde commented
> initiate_connect(...) is only there for the test setup. It should be removed from the public API to avoid confusion. Even worse, the slightly different return type of connect_without_code(...) has been added to a public API only for purpose of internal testing.

This is news to me, could you please elaborate? Unifying the return types / getting rid of `initiate_connect` would indeed be an interesting improvement.

2023-05-04 06:49 UTC, wuan commented
You are right, that is a general requirement. The basic problem seems to be that we want to access the generated code as a partial result, before we open the wormhole connection, which blocks until the other side enters exactly this code. That is for me the reason why we have that asymmetry in return types.

To overcome this, I now split up in creating the mailbox connection and creating the wormhole:

Setting up the wormhole on the code generating side looks like this:
```
let mailbox_connection = MailboxConnection::create(app_config, code_length).await?;
let code = mailbox_connection.code.clone();
<display/send code>
let wormhole = Wormhole::connect(mailbox_connection).await?;
```

and on the other side like this:

```
let mailbox_connection = MailboxConnection::connect(app_config, code, false).await?;
let wormhole = Wormhole::connect(mailbox_connection).await?;
```

which can even be simplified to, if you do not care about the welcome message:

```
let wormhole = Wormhole::connect_with_code(mailbox_connection, code, false).await?;
```

Does that help to make the steps more clear?

Names are still "in progress", better ideas are welcom.

2023-05-04 09:54 UTC, piegamesde requested changes
Looks interesting on the first look. Maybe always having a two-step connection even for the receive side is a good thing – with the old API, the receiver would only print the welcome message after the entire handshake had gone through. Now, it is more symmetric between both sides.

> which can even be simplified to the following, if you do not care about the welcome message:

I thought about proposing `mailbox_connection.connect_wormhole()` for that purpose, but then noticed that we have literally no use case for this as we always print the welcome message, and we should not encourage ignoring it

2023-05-04 09:54 UTC, piegamesde commented on src/core.rs
> +        if allocate {
```suggestion
        if !allocate {
```

The semantics have flipped with the rename

2023-05-04 09:54 UTC, piegamesde commented on src/core.rs
> +        mailbox_connection: MailboxConnection<impl serde::Serialize + Send + Sync + 'static>,
```suggestion
        MailboxConnection {
            config,
            mut server,
            mailbox: _mailbox,
            code,
            welcome: _welcome,
        }: MailboxConnection<impl serde::Serialize + Send + Sync + 'static>,
```

I think nowadays one can destructure function arguments like this? Not sure if it is an improvement over doing it in a let bindings below. (Also, you can use `..` to ignore all remaining fields without having to list them)

2023-05-04 09:54 UTC, piegamesde commented on src/core.rs
> +pub struct MailboxConnection<V: serde::Serialize + Send + Sync + 'static> {
`MailboxServer`? `MailboxServerConnection`?

2023-05-04 09:54 UTC, piegamesde commented on src/core.rs
>  }
This struct can be removed now I think

2023-05-04 12:28 UTC, wuan commented on src/core.rs
> +        if allocate {
Thanks, this should be fixed now and we have a pair of tests to verify that behaviour.

2023-05-04 12:32 UTC, wuan commented on src/core.rs
> +        mailbox_connection: MailboxConnection<impl serde::Serialize + Send + Sync + 'static>,
Yes, did not now that. This works great, especially the `..`.

2023-05-04 12:33 UTC, wuan commented on src/core.rs
> +pub struct MailboxConnection<V: serde::Serialize + Send + Sync + 'static> {
So far I thought that the `MailboxServer` helps to create a `Mailbox` and here we have a connection to that `Mailbox`: `MailboxConnection`. I'm fine with both.

2023-05-04 12:38 UTC, wuan commented on src/core.rs
>  }
It is still being used with the deprecated method(s). Just added a deprecated annotation here as well.

2023-05-05 05:56 UTC, wuan commented on src/core.rs
> +        if allocate {
As it would change the behaviour I will revert `connect_with_code(...)` to use `expect_claimed_nameplate` and mark it as deprecated. That should allow a smooth transition to the `allocate` argument.

2023-05-05 09:19 UTC, piegamesde reviewed
Code looking good so far. The doc comments still need adapting though

2023-05-05 09:19 UTC, piegamesde commented on src/core/test.rs
> +    // the max nameplate number is 999, so this will not impact a real nameplate
We use a custom appid for tests, so there were no collisions in the first place

2023-05-05 09:34 UTC, wuan commented on src/core/test.rs
> +    // the max nameplate number is 999, so this will not impact a real nameplate
Yes, that comment has already been there, can delete that.

2023-05-05 17:05 UTC, piegamesde commented on src/core/test.rs
> +pub async fn test_file_rust2rust_deprecated() -> eyre::Result<()> {
Oops, should have been `#[allow(deprecated)]` instead; compiler is not happy at all

2023-05-05 20:44 UTC, wuan commented on src/core/test.rs
> +pub async fn test_file_rust2rust_deprecated() -> eyre::Result<()> {
That should be fixed now.

2023-05-05 20:45 UTC, wuan commented
> Code looking good so far. The doc comments still need adapting though

After having lots of fun with doctests there should be some more doc comments now.

2023-05-05 21:50 UTC, meejah commented
Would being more like the Python API help here?

There, we do not conflate "connecting" or "creating" the Wormhole with the code at all -- instead you must call `.set_code()` or `.allocate_code()` (i.e. depending on whether you have one or wish to create one) at some point, before calling `.get_code()` (all code-paths call this).

This is more like "Builder" I suppose, superficially. But "the wormhole" has state, so there's no real getting around that.

You could also get rid of the bool in the API by declaring "the code" as a `Maybe`: if it's `Nothing` then allocate one. (I guess in Rust that's spelled `Option` and `None`).

2023-05-05 21:57 UTC, wuan commented
> You could also get rid of the bool in the API by declaring "the code" as a `Maybe`: if it's `Nothing` then allocate one. (I guess in Rust that's spelled `Option` and `None`).

That sounds different. In this case we always have a code. The boolean only determines the behaviour if the nameplate cannot be found: create it (`true`) or fail (`false`).

2023-05-05 22:29 UTC, meejah commented
How do you know if the nameplate can be found without trying to `claim` it?

2023-05-05 22:40 UTC, piegamesde commented
Yeah that is a temporary until we have the allocate flag in the `claim` command merged

2023-05-05 22:43 UTC, meejah commented
I don't anticipate merging that anytime soon; it breaks the protocol. But, okay, understood.

2023-05-06 04:46 UTC, wuan commented
> I don't anticipate merging that anytime soon; it breaks the protocol. But, okay, understood.

This PR only **renames** and inverts the semantics of the boolean parameter, it does not change functionality. We can even rename and invert the parameter to have no change at all.

2023-05-06 04:51 UTC, meejah commented
> This PR only renames and inverts the semantics [..]

I'm not talking about this PR in the sentence you quote.

2023-05-06 04:57 UTC, wuan commented
> I'm not talking about this PR in the sentence you quote.

Then I propose to add a reference to an issue / PR to link this discussion there.

2023-05-07 09:11 UTC, piegamesde requested changes

2023-05-07 09:11 UTC, piegamesde commented on src/core.rs
> +    /// ```
```suggestion
    /// ```no_run
```

Probably better to not run these tests, because unlike the "real" tests these use the production configuration (by design). Theoretically, you could silently set up a test mock so that the example still remains copypastable, but honestly that's probably not worth the effort.

2023-05-07 09:11 UTC, piegamesde commented on src/core.rs
> +    /// use futures::executor;
It's better to try and hide the setup stuff which is not directly linked to the usage. The example should be easy to copy-paste, and for that we may assume that the developer is already in an appropriate context (in this case, async and returning a `Result`).

You can have hidden setup lines by prefixing them with `#`, and the `async_std` crate does the following for their examples (I just adapted the Result type):

```suggestion
    /// # fn main() -> eyre::Result<()> { async_std::task::block_on(async {
```

(Full reference: https://docs.rs/async-std/latest/src/async_std/net/tcp/stream.rs.html#62-72)

2023-05-07 19:25 UTC, wuan commented on src/core.rs
> +    /// ```
I already tried that, but it seemed to have no effect. Will add the `no_run` again.

2023-05-07 19:32 UTC, wuan commented on src/core.rs
> +    /// use futures::executor;
Fully agree here. Thanks for the hint. This works great.

2023-05-07 20:10 UTC, wuan commented on src/core.rs
> +    /// returns: Result<MailboxConnection<V>, WormholeError>
That line has been autogenerated by the IDE. Will drop all of them.

2023-05-08 18:09 UTC, meejah commented
> > I'm not talking about this PR in the sentence you quote.
> 
> Then I propose to add a reference to an issue / PR to link this discussion there.

I don't think it's relevant, but others can link it if they believe it is. I was just trying to clarify here that the PR piegames mentioned (and to which my reply pertained) wasn't _this_ one, as you seemed to believe with your reply.

The only relevance is that the "depend on `list` working" code in this repository is intended to be a temporary situation.

2023-05-09 19:24 UTC, piegamesde approved these changes
Looking good, only nits left. Cargo fmt is unhappy, but if you tell me that it runs fine on your machine then that's sufficient (we unfortunately have to use unstable for fmt so you may just have a different version with a different output).

Feel free to make the commit history tidy otherwise I'll just squash it into one commit. (I like "atomic" commits but arguably this entire PR is pretty atomic so it's fine)

2023-05-09 20:55 UTC, wuan commented
Thanks, rebased and squashed all commits.

2023-05-09 21:09 UTC, merged